name: CI/CD Workflow for .NET 6

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get Jenkins Crumb
      id: get-crumb
      run: |
        CRUMB=$(curl -u "${{ secrets.JENKINS_USERNAME }}:${{ secrets.JENKINS_TOKEN }}" -s 'http://103.160.62.183:8080/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,":",//crumb)')
        echo "::set-output name=crumb::$CRUMB"


    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'

    - name: Build project
      run: dotnet build --configuration Release

    - name: Publish project
      run: dotnet publish --configuration Release --output ./publish

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # Build Docker image dengan tag latest
    - name: Build Docker image
      run: docker build -t asfi26/simpleapi:latest .

    # Push Docker image dengan tag latest
    - name: Push Docker image to Docker Hub
      run: docker push asfi26/simpleapi:latest

    - name: Trigger Jenkins job
      run: |
        curl -u "${{ secrets.JENKINS_USERNAME }}:${{ secrets.JENKINS_TOKEN }}" -H "${{ steps.get-crumb.outputs.crumb }}" -X POST http://103.160.62.183:8080/job/myapiapp-deployment/build?token=11f071c7669ea30df36e65dd7fa392d28f
